### ISSUE TITLE
Not working with Angular RC1

### ISSUE THREAD

**Issue by MaestroJurko** [Pasvaz/bindonce#105]
TypeError: undefined is not a function
    at bindonceDirective.link (http://127.0.0.1:8282/js/Components/angular-bindonce/bindonce.js:225:26)

**Comment by MaestroJurko** [comment]
angular.extend(this, ctrl); instead of return ctrl

**Comment by metamatt** [comment]
I can confirm the problem (I saw the same symptom on a different line, any reference to bindonceController.someFunction could fail this way) and the fix works. Thanks.

**Comment by mikcox** [comment]
I'm having the same issue, in the same way as above, at bindonce.js:230:25.  Has there been a fix implemented for this?

Thanks!

**Comment by zeitiger** [comment]
Fine that I'm not alone with that problem. 

bower.json
"angular-bindonce": "git@github.com:zeitiger/bindonce.git#6b5fafe57ac02618f61cac771471f96af454b7f6"

**Comment by mattsahr** [comment]
Somewhere around line 217 of bindonce.js you will find this line

```
return ctrl;
```

Change it to this....

```
angular.extend(this, ctrl); 
```

And you should be fixed.

**Comment by joeltello** [comment]
any updates?

**Comment by paglias** [comment]
:+1:

**Comment by thorning** [comment]
The fix from mattsahr worked for me, thanks

**Comment by mikcox** [comment]
For what it's worth, Angular 1.3 is implementing built-in functionality for binding once, which seems to have mostly deprecated this directive in the application I am building.  See https://github.com/angular/angular.js/commit/cee429f0aaebf32ef1c9aedd8447a48f163dd0a4 for details.

**Comment by amit777** [comment]
mattsahr's fix worked for me as well..
