### ISSUE TITLE
bindonce doesn't work without "watched value" when used in combination with jade

### ISSUE THREAD

**Issue by timjnh** [Pasvaz/bindonce#107]
Jade will produce bindonce="bindonce" from a 'bindonce' attribute with no value associated with it.  For example:

`div(bindonce)`
`a(bo-title="model.title") foo`

will result in:

`<div bindonce="bindonce"><a bo-title="model.title">foo</a></div>`

The results is that bindonce waits for a value to appear in the scope for "bindonce" which will never happen.

I know this isn't really a bindonce bug but it threw me off a bit at first.  Thanks!

**Comment by Pasvaz** [comment]
what about `div(bindonce="")`

**Comment by ognus** [comment]
Hi, I had the same problem as @timjnh using `div(bindonce)` in jade.

But `div(bindonce="")` works fine.

**Comment by timjnh** [comment]
Thanks!  Good suggestion guys.
