### ISSUE TITLE
Create a new release from master

### ISSUE THREAD

**Issue by chrisdwheatley** [Pasvaz/bindonce#112]
Any possibility of creating a new release from master & pushing to Bower & npm?

It'd allow our team to upgrade to Angular 1.3 without having to depend upon a commit hash in our own bower.json.

**Comment by aptx4869** [comment]
+1

**Comment by chuckconway** [comment]
+1

**Comment by thorning** [comment]
+1

**Comment by joeltello** [comment]
+1

**Comment by Pasvaz** [comment]
I'll do it this week end. Sorry for the delay but right now I'm extremely busy

**Comment by Pasvaz** [comment]
Released (bdfc43b59591d64a9f0b9c9991513b2231cb84be)
