### ISSUE TITLE
No controller: bindonce

### ISSUE THREAD

**Issue by allenwyma** [Pasvaz/bindonce#16]
I'm getting this error of "No controller: bindonce" when I try to use bindonce. I have included it in my module as a dependency:

``` coffeescript
window.appular = angular.module("app", ['ngResource', 'ngSanitize', 'pasvaz.bindonce']).config [...
```

And I checked and the bindonce.js I got from the master branch is in the HTML page. any ideas?

here is one example that I tried to use in HTML:

``` html
<span class="glyphicon glyphicon-info-sign" bo-show="shift.remarks.length > 0">
```

**Comment by Pasvaz** [comment]
You need to use at least one bindonce attribute, ie:

``` html
<span bindonce class="glyphicon glyphicon-info-sign" bo-show="shift.remarks.length > 0">
```

or better:

``` html
<span bindonce="shift.remarks" class="glyphicon glyphicon-info-sign" bo-show="shift.remarks.length > 0">
```

or also:

``` html
<div bindonce="shift">
   <span class="glyphicon glyphicon-info-sign" bo-show="shift.remarks.length > 0">
   <span class="..." bo-show="shift.xxx">
   ...
```

If you omit the bindonce value, any bo-\* attribute will be evaluated immediately, if you specify the bindonce value the bo-\* attributes will be evaluated when the bindonce object become valid. For instance, in the above example, bindonce="shift" means that bo-show will wait until shift is defined, when it happens it run the bo-show expression once and die.
