### ISSUE TITLE
Controller can't be found

### ISSUE THREAD

**Issue by designbyadrian** [Pasvaz/bindonce#17]
Hello! I'm running Angular 1.2rc1 and getting this error with all BO directives:

Error: [$compile:ctreq] Controller 'bind once', required by directive 'boText', can't be found!

The HTML that triggers it is just <div bo-text="weekend.allowance"></div>

I've added bo as an app dependency, what else do I need to do?

**Comment by Pasvaz** [comment]
Please check this issue #16 , if your problem is different attach your code or even better create a plunker/fiddler.

**Comment by designbyadrian** [comment]
I'm deeply sorry, I didn't see that there was a 'closed issues' section. The directive binding was exactly what I needed. Thank you! Feel free to delete this as it is now a duplicate of #16
