### ISSUE TITLE
bo-click event

### ISSUE THREAD

**Issue by ghost** [Pasvaz/bindonce#18]
Hi,

I'd like to add button events, e.g. bo-click-i='..'

This seems to work...

```
                        case 'click':
                            binder.element.on( binder.attr, function (event)
                            {
                                $scope.$eval( value );
                            }
                            );
```

...

```
{ directiveName: 'boClickI', attribute: 'click', interpolate: true  },
```

**Comment by Pasvaz** [comment]
Why do you need bo-click when you can use ng-click?

**Comment by ghost** [comment]
I'm adding interpolated content to parameters of an ng-click, and they don't change again, so I don't want them watched.

e.g. bo-click-i="myFunction({{$index}})"

Just trying to get maximum performance, and I have a page with potentially a lot of buttons.

**Comment by Pasvaz** [comment]
The interpolation itself is a watch, even if you use bo-click Angular keeps watching the interpolated value.

**Comment by ghost** [comment]
Oh ok. Thanks for that.
