### ISSUE TITLE
0.2.1 throws 'cannot call method $eval of undefined'

### ISSUE THREAD

**Issue by wan54** [Pasvaz/bindonce#20]
Update the existing js with this version and you'll see the exceptions in the browser console -- was using the latest Chrome

**Comment by Pasvaz** [comment]
can you provide some code to reproduce the issue?

**Comment by cm325** [comment]
using the correct for loop for the array from #22  fixed this for me-

**Comment by Pasvaz** [comment]
fixed by the #22
