### ISSUE TITLE
SOLVED: Controller 'bindonce', required by directive 'undefined', can't be found!

### ISSUE THREAD

**Issue by elicriffield** [Pasvaz/bindonce#26]
Maybe i'm missing something simple. 
It's loading the file and the the module is defined but i still get one

Error: [$compile:ctreq] Controller 'bindonce', required by directive 'undefined', can't be found!

for every bo-\* directive i use.

--- This appears to be https://github.com/Pasvaz/bindonce/issues/16

**Comment by Pasvaz** [comment]
Yes, indeed :)
