### ISSUE TITLE
Add history/changelog to readme

### ISSUE THREAD

**Issue by FGRibreau** [Pasvaz/bindonce#27]
... and specify that `bo-for` was removed between 0.1.1 and 0.2.1, the work-around is to replace `bo-for` by `bo-attr bo-attr-for`.

**Comment by Pasvaz** [comment]
A changelog would be neat, however as long as I remember `bo-for` never existed.

**Comment by FGRibreau** [comment]
You're right, I forgot I added bo-for myself :)

**Comment by Pasvaz** [comment]
I guess it was a sort of cycle/repeater, if you think other can take benefit from it, feel free to commit it.
