### ISSUE TITLE
Infinite recursion when using boText, boIf in ngRepeat

### ISSUE THREAD

**Issue by mik01aj** [Pasvaz/bindonce#28]
I got an infinite recursion when using some directives from bindonce. The code looks like this:

```
<ul bindonce="fieldsData">
    <li ng-repeat="field in fieldsData">
        <span bo-if="field.type === 'string'" class="value" bo-text="field.value"></span>
        <ul bo-if="field.type === 'array'" class="inline-list value">
            <li ng-repeat="listItem in field.value">{{ listItem }}</li>
        </ul>
    </li>
</ul>
```

And I get an infinite recursion as shown on the screenshot (notice the cycle in stacktrace).

![screenshot from 2013-10-02 15 42 19](https://f.cloud.github.com/assets/3027415/1253718/05357472-2b6a-11e3-8119-ca65cf30aa64.png)

**Comment by Pasvaz** [comment]
this is related to #25

**Comment by jelinson** [comment]
:+1:

**Comment by akarelas** [comment]
:+1:
