### ISSUE TITLE
boHref breaks inside boIf

### ISSUE THREAD

**Issue by mik01aj** [Pasvaz/bindonce#29]
see plunkr: http://plnkr.co/edit/9QzBPAeY6M31g8a7YuxQ?p=preview

This ends up with an error: `Error: [$compile:ctreq] Controller 'bindonce', required by directive 'a', can't be found!`.

If you remove the `bo-if`, however, `bo-href` works normally.

**Comment by mik01aj** [comment]
hmm, looks like duplicate of #25...

**Comment by Pasvaz** [comment]
unfortunately bo-if is broken, I'll fix it asap as I said here #25

**Comment by akarelas** [comment]
Please fix bo-if...
