### ISSUE TITLE
angular version in bower.json

### ISSUE THREAD

**Issue by Kagami** [Pasvaz/bindonce#31]
Could you please specify less restrictive version dependency for angular in bower.json? `>=1` would be fine.
angular 1.2 will be here soon, also people use bindonce with 1.1.x without problems as well as I am.

**Comment by MrIsaacs** [comment]
As angular 1.2.0 (angular/angular.js@6a0aff84c4176535d1141bb47f3c74996227100c) is released 6 days ago it would be nice if you can update bower in your repository. I've installed `bindonce` and as i thought it would be version 0.2.1 but in the source code of `/angular-bindonce/bindonce.js` it is written as 0.1.1.
Which version is the right one?

**Comment by Pasvaz** [comment]
@Kagami I fixed the version issue, @MrIsaacs the source code has the current version as well, where did you see 0.1.1 exactly?

**Comment by Kagami** [comment]
Could you also mark commit 88ab175d09da3e6f7574c1c3473abac6f2119567 with the 0.2.2 tag? Otherwise bower can't install it:

```
% bower install
bower not-cached    git://github.com/Pasvaz/bindonce.git#0.2.2
bower resolve       git://github.com/Pasvaz/bindonce.git#0.2.2
bower ENORESTARGET  No tag found that was able to satisfy 0.2.2

Additional error details:
Available versions: 0.2.1, 0.2.0
```

**Comment by Pasvaz** [comment]
done

**Comment by Kagami** [comment]
Thanks!
