### ISSUE TITLE
filtering

### ISSUE THREAD

**Issue by axedre** [Pasvaz/bindonce#33]
Hi, first of all congratulations for your script, pretty nifty indeed!
I'd like to ask if it is currently possible to use angular filters (even custom ones) within bindonce.
I'd like to be able to use bindonce to convert i.e. the following tag:

```
<div ng-repeat="someVar in someVarArray">
    //...
    <span>{{someVar | myFilter}}</span>
    //...
</div>
```

I tried with:

```
<div bindonce ng-repeat="someVar in someVarArray">
    //...
    <span bo-text="$filter('myFilter')(someVar)"></span>
    //...
</div>
```

but unfortunately it didn't work. Hints?
Thanks in advance,

Andy

**Comment by axedre** [comment]
Never mind, I figured it's as simple as writing:

```
<div bindonce ng-repeat="someVar in someVarArray">
    //...
    <span bo-text="someVar | myFilter"></span>
    //...
</div>
```

Thanks and keep up the good work! :)

**Comment by akarelas** [comment]
It should be clearer in the bindonce documentation that you can use filters that way.

**Comment by akarelas** [comment]
But it isn't

**Comment by mehaase** [comment]
Thanks for posting this! I was wondering the same thing.

**Comment by Pasvaz** [comment]
@akarelas I agree with you, anyway one nice feature of Github is that it allows you to create a pull request and submit your changes so you could edit the readme and submit the PR, I'll accept it straight away.

**Comment by ncammarata** [comment]
This isn't really a bindonce feature, it's Angular's. You can use filters anywhere.
Example: http://jsfiddle.net/HB7LU/2284/

**Comment by mehaase** [comment]
We all know it's a feature of Angular, but the syntax is different between most Angular directives and most bindonce directives. That's what this question was about.

**Comment by ncammarata** [comment]
Is there any way to run a filter on a attribute you don't have control over?

``` html
<dog bark="barkID | expensiveGetBark"></dog>
```

I would like to only run expensiveGetBark once when barkID is set.

**Comment by akarelas** [comment]
Have you tried the bo-attr feature?

**Comment by ncammarata** [comment]
This is essentially the issue I am running into:
http://jsfiddle.net/hgqs9/3/

**Comment by ncammarata** [comment]
I believe it's because the scope isn't being applied after the attribute is set

**Comment by rileylark** [comment]
@ncammarata Ideally angular would only `$watch('barkID')` and trust your `expensiveGetBark` to stay the same until barkID changes - I just ran into this problem myself!

My workaround was to create another $scope property in a controller, e.g.

```
$scope.$watch('barkID', function(id) {
    $scope.bark = expensiveGetBark(id);
});
```

Then later you can use `<dog bark="bark"/>`.  Kind of a pain!  But, this workaround works with bindonce and normal angular directives.  Until Angular has a way of specifying that your filter is idempotent I think we'll have to keep doing this :(
