### ISSUE TITLE
Could change ng- attributes automatically

### ISSUE THREAD

**Issue by r3m0t** [Pasvaz/bindonce#37]
As this very silly plunkr demonstrates it's possible (theoretically) to go through all the children in the template when compiling, and switch the `ng-` directives for `bo-` ones.

Is there a reason not to offer this or just do it always?

http://plnkr.co/edit/ay8UrdqNSFi8WxHaGlAn?p=preview

**Comment by Pasvaz** [comment]
Sure it would be possible, but it is a wrong approach, bo- is not a replacement for ng-. 
If you would use bo- indiscriminately you would just break your app because all the bindings would become static. It's up to the developer to decide when a binding must be static or not.
