### ISSUE TITLE
any way to support rerender when needed

### ISSUE THREAD

**Issue by shaokun** [Pasvaz/bindonce#4]
assumed that we have

``` html
<ng-repeat="product in products">
<div bindonce="product">
  <span bo-text="product.name" />
  <span bo-text="product.desc" />
</div>
</ng-repeat>
```

and if I replace products with a new array, can we somehow let bindonce rerender again?

**Comment by Pasvaz** [comment]
Yes, the bindings inside a repeater are refreshed every time the collection changes, so your example works as it is.

**Comment by cm325** [comment]
What about a way to rerender bindings that aren't in a repeater? In my app, changes are infrequent, I'm liking the ability to bindonce, but occasionally, something might change, and it would be nice to manually rerender-

**Comment by Pasvaz** [comment]
it was something I've considered at the beginning, but using a callback or a broadcast call in presence of many binding would be a waste of resource, never the less we could make it optional and turn it on only if needed, I'll think about it, thank you for pointing it out.
