### ISSUE TITLE
Transparent Character

### ISSUE THREAD

**Issue by hikkyu** [Pasvaz/bindonce#5]
Hello,

A transparent character break the build at line 22.

Thank's
Hikkyu

**Comment by Pasvaz** [comment]
I downloaded the file and tested it and everything seem fine, can you provide mode details about this issue?

**Comment by hikkyu** [comment]
Yep of course! 

If you try to delete ligne 22 you need to delete 3 times (that's the transparent character).
In a IDE like php storm you can see it.

**Comment by Pasvaz** [comment]
Got it, I checked the file with my editor, github didn't show it. Thank you for reporting it
