### ISSUE TITLE
bind-again on event

### ISSUE THREAD

**Issue by rileylark** [Pasvaz/bindonce#50]
I have a lot of data that _occasionally_ changes, but is very expensive to $watch - 500kb data urls.  Even with only a dozen on the screen my 2014 MBP slows to a few FPS.

I am interested in firing an event when the user changes the image (I can isolate all of the ways the image might change).  The event would alert bindonce that it should re-fetch its value and set it again on all its children.

Does this seem like a valuable extension?  I can make an initial attempt at the code and submit a PR if it seems like this would be inline with the project.

Thanks!

**Comment by Pasvaz** [comment]
Hi @rileylark, this feature is under development, I think I'll push it this weekend.
