### ISSUE TITLE
Support for bo-style-i and bo-class-i

### ISSUE THREAD

**Issue by MichielDeMey** [Pasvaz/bindonce#58]
Sorry for creating yet another issue, but it would only seem logical to have a bo-style and bo-class that support interpolation.

So that we can use something along the lines of `bo-class-i="size-{{element.size}}"` and

```
bo-style-i="{'background-image': {{element.image}}, 'background-color': {{element.color}}}"
```

Right now I can work around this issue by using a function that returns the values.

For example:

``` HTML
bo-style="getAppImgStyle(app)"
```

``` javascript
$scope.getAppImgStyle = function(app) {
      return {
        'background-image': 'url(' + app.image + ')',
        'background-color': app.color
      };
    };
```

But this workaround kind of pollutes the directive/controller with unnecessary functions.

**Comment by Pasvaz** [comment]
as you might know your workaround doesn't use any watcher, the function is fired once, when bindonce runs the binder while `bo-class-i="size-{{element.size}}"` still use 1 Watcher for the interpolation. I'm wondering why you prefer the latter. Also the directive `bo-class-i="size-{{element.size}}"` can be written to avoid watchers in this way `bo-class="'size-'+element.size"`

**Comment by MichielDeMey** [comment]
Oh I see.

I wasn't aware that I could concatenate string inside `bo-*="  "`.
That's basically why I created the function in the first place.

But then, is there a difference between `bo-*-i="object.property "` and `ng-*="{{object.property}}"`?

**Comment by Pasvaz** [comment]
well `bo-*-i="object.property "` doesn't make sense, if you use the `-i` version of the `bo-*` attributes it means that you need to use interpolation, so if your question is if there is a difference between `bo-*-i="{{object.property}}"` and the `ng-*="{{object.property}}"` the answer is: yes but not always, the difference is that in some cases `bo-*-i` uses one watcher less than the equivalent `ng-*`, but generally the use of `bo-*-i` is higly discouraged, you should avoid interpolation as long as you want to get rid of watchers.

**Comment by braco** [comment]
So what is the preferred method to get a background: url({{bind}}) with bo-*?
