### ISSUE TITLE
Being able to use bindonce through a custom interpolation expression, rather than through DOM directives

### ISSUE THREAD

**Issue by tennisgent** [Pasvaz/bindonce#59]
This is a feature request, though I'm not really sure how you would go about doing it.  I've done some research, and it hasn't really gotten me anywhere, so I figured I'd post this here in case anyone has any suggestions on how to create this.  I ask for your patience while I explain our problem:

I love the idea behind `bindonce`. In our app, we have a TON of content that gets loaded asynchronously from our REST api, and then gets plugged into the DOM once the api call has returned.  For ease-of-use, we use interpolated expressions to bind that content from the `$scope` to the DOM so that it is displayed to the user (which is obviously what `$watchers` and interpolation was designed for).  The problem, as stated perfectly in your README, is that the content never changes again once it's loaded from the api.  But we still end up with countless watchers all over the place that are watching for changes to `$scope` properties that are never going to change.  

In comes `bindonce` to save the day.  It solves this problem beautifully.  But I have one minor complaint.  Most of the dynamic api content that I'm referring to is just text.  So we use the `bo-text` directive a lot.  The problem with the `bo-text` directive is that its just that.  A directive.  And so in order to use it, you have to put it on some DOM element, which we typically end up using `<span>`s for.  We have lots of `<span bo-text="obj.name"></span>` statements all over in our markup.  That can get really annoying and verbose to have to use all that markup to replace what we used to do with `{{obj.name}}'.

So my feature request:  does anyone know of a way to do custom interpolated binding with angular?  What I would like to do is to be able to use some special binding syntax to indicate that I want to interpolate the expression, but using the `bindonce` "no watcher" technique, rather than the typical angular method.

For example, I'd like to be able to do the following:

``` html
<div class="my-div">
    <label>Some Text</label>
    {{{obj.name}}} can be used with {{{obj.value}}}
</div>
```

Using the custom triple-brace syntax would automatically do a "bind once" for the expression and would then remove the watcher.  And it doesn't necessarily have to be triple braces, it could be any sort of parsing delimiter (such as `<%`, `%>` or `{[{`, `}]}` or whatever).

Is that even possible?  I tried researching more about angular's `$interpolate` service and tried creating a decorator that would decorate the `$interpolateProvider` with this extra functionality, but I couldn't find a way to do it.  Any ideas?

Thanks.

**Comment by Pasvaz** [comment]
have checked this issue #47

**Comment by Pasvaz** [comment]
Feel free to re-open this issue when you want to add other consideration, I'm closing it until then.

**Comment by fredyang** [comment]
I think this is really a good feature request, but I think it is impossible without modifying the source code in $CompileProvier in core anguarjs. So it is can not be achieve by an external module.
