### ISSUE TITLE
bo-style returns [object object] instead of something usable

### ISSUE THREAD

**Issue by Charuru** [Pasvaz/bindonce#6]
bo-style returns [object object] instead of something usable

You can't easily convert the style into a string either, I'm not sure what the problem is but angular should have taken care of this?

**Comment by Pasvaz** [comment]
You are right, it was added as simple attribute, I'll rewrite it.

**Comment by Charuru** [comment]
Yep I also dealt with this in my watchFighters fork:

https://github.com/Charuru/angular-watchFighters/commit/fd204f533ba470c959d7b94fd022dcc6ecfcc2ae
