### ISSUE TITLE
syntax error in ie

### ISSUE THREAD

**Issue by raghb1** [Pasvaz/bindonce#61]
{ directiveName: 'boSwitchWhen', transclude: 'element', priority: 800, require: '^boSwitch', },
{ directiveName: 'boSwitchDefault', transclude: 'element', priority: 800, require: '^boSwitch', }

IE browser is throwing syntax error at the above line of code. 
The comma at the end needs to be removed. Please re-release this version with the fix.

**Comment by Pasvaz** [comment]
thank you for reporting it @raghb1
