### ISSUE TITLE
Question for custom directives

### ISSUE THREAD

**Issue by JanStevens** [Pasvaz/bindonce#62]
Hello,

I would like to use this princable in my own custom directive. It simple checks if an url is allowed (by looking it up in an array returned from the server) to determine if it should show a link or just a span tag with the contents.

When the permissions get updated I fire an event and the directive recalculates the permissions.

``` HTML
<span auth-link-to url="#/{{user}}/cookies/{{cookies.id}}">
      {{cookies.name}}
    </span>
```

The directive

``` coffee
Directives.directive('AuthLinkTo', ['Authorization',
  (Authorization) ->
    checkUrl = (rawUrl) ->
      if rawUrl?
        allowed = Authorization.allow(rawUrl)
      else
        allowed = false
        console.warn "No url specified in auth-link-to, permission set to false"

      return {
        url: (if allowed then rawUrl else null),
        allowed: allowed
      }


    link = (scope, element, attrs) ->
      result = checkUrl(scope.url)
      scope.allowed = result.allowed
      scope.url = result.url

      scope.$on('authorizationUpdate', ->
        result = checkUrl(scope.url)
        scope.allowed = result.allowed
        scope.url = result.url
      )


    return {
      restrict: 'E',
      scope: {
        url: '@'
      },
      link: link,
      transclude: true,
      priority: 0,
      replace: true,
      templateUrl: "templates/directives/auth_link_to"
    }
  ])

```

So how can I prevent the creation of any watcher in my code (the url for example is always static, only the permissions in the service maybe change over time)

Thanks a lot for the awesome speed improvements!

**Comment by Pasvaz** [comment]
Your url attribute uses interpolation therefore some watchers are created, in order to avoid it, if the `url` never changes, you can remove the interpolation and use `scope.$eval` inside the directive to check if the url is allowed. For instance you can use the attribute like this: 
`<span auth-link-to url="'#/' + user + '/cookies/' + cookies.id">` and get its value with `scope.eval(attrs.url)`
