### ISSUE TITLE
Does not allow to create img with base64 src

### ISSUE THREAD

**Issue by igormisha** [Pasvaz/bindonce#65]
First I created template like this:

```
<img src="data:image/jpeg;base64,{{new.ImageSmall}}">
```

And the angularjs databinding with image src worked as expected.

Then I tried to use this module with img src attributes, which contain base64 string, presenting image resource, like this:

```
<img bo-src="'data:image/jpeg;base64,' + new.ImageSmall">
```

But this doesn't work. Is there another way to pass expression to img src?

**Comment by Pasvaz** [comment]
it should work, can you create a [plunker](plnkr.co) so I can test it?

**Comment by igormisha** [comment]
Sure, here it is: http://plnkr.co/edit/BgiM8lkVg8XUQkbgwvQt?p=preview

**Comment by igormisha** [comment]
It appeared that bo-src is not enough, it was neccessary to add 'bindonce' attribute to img tag or it's parent. My fault, everything works just fine! Thanks for quick reply!

**Comment by Pasvaz** [comment]
no problem, glad you fixed it.
