### ISSUE TITLE
Are embed ng-repeat working with bindonce directive ?

### ISSUE THREAD

**Issue by mparpaillon** [Pasvaz/bindonce#66]
Hi,

If I want to list a collection of phone numbers for a collection of users what should I do to limit the numbers of $watch ?

For example:

``` html
<div bindonce ng-repeat="user in users">
    <div bo-text="user.name"></div>
    <ul>
        <li bindonce ng-repeat="number in user.phonenumbers">
            <div bo-text="number.value"></div>
        </li>
    </ul>
</div>
```

It seems that I can't prevent the second ng-repeat from adding watchers.

Hope my question is clear.
Thanks

**Comment by lorenzhs** [comment]
Do the phone numbers change? If not, you could use bo-repeat.

**Comment by mparpaillon** [comment]
bo-repeat ? Damn I didn't see that in the doc...

**Comment by mparpaillon** [comment]
I don't think the bo-repeat directive exists...

**Comment by lorenzhs** [comment]
Wait. I am a bit confused right now. Sorry.

**Comment by lorenzhs** [comment]
Ah right, I was living in the future, see #10. Sorry for that.

**Comment by mparpaillon** [comment]
Mmmm ok. The future looks bright.

I close for duplicate #10
