### ISSUE TITLE
$sce and bindonce?

### ISSUE THREAD

**Issue by fxck** [Pasvaz/bindonce#68]
I'm trying to print something that's got a filter, which returns it as `$sce.trustAsHtml()`, using `bo-html`, it works fine using `ng-bind-html` but doesn't show anything, nor throws any error using `bo-html`..

**Comment by Pasvaz** [comment]
@fxck can you please create a plnkr which I can play with?

**Comment by fxck** [comment]
Sure @Pasvaz, there you go http://plnkr.co/edit/AbidYr9poEE43BHVjvyb?p=preview

// edit
it actually seems to work on plunker, so it might be some bogus in my app, closing the issue, thanks!
