### ISSUE TITLE
cdn js error

### ISSUE THREAD

**Issue by apneadiving** [Pasvaz/bindonce#85]
When requiring the minified version of the plugin on cdnjs (http://cdnjs.com/libraries/angular-bindonce):

```
//cdnjs.cloudflare.com/ajax/libs/angular-bindonce/0.2.2/angular-bindonce.min.js
```

I've got:
Uncaught SyntaxError: Unexpected token ( angular-bindonce.min.js:1)

Works fine with the non minified though.

**Comment by Pasvaz** [comment]
That version is really old, don't use that, use bower or download the current trunk.

**Comment by apneadiving** [comment]
ok :)
